server:
  port: ${PORT:8080}
spring:
  application:
    name: spring-feign
  profiles:
    active: dev
  cloud:
    openfeign:
      httpclient:
        hc5:
          enabled: true
feign:
  client:
    config:
      accounts-service:
        url: https://326d58b9-9aef-42f9-8c54-bf26235cc228.mock.pstmn.io/
        connectTimeout: 30
        readTimeout: 30
      profiles-service:
        url: https://5ae77e76-f200-4175-a9fc-e54b0bfc3a28.mock.pstmn.io/
        connectTimeout: 30
        readTimeout: 30

logging:
  level:
    com.tad.springfeign: INFO
